fizzbuzz.rb is completed !
Cephas604/ruby-practices pull request #2
Opened 2022-08-12 11:21 UTC by Cephas604

2022-08-13 04:48 UTC, func09 requested changes
* [ ] 他の提出物を混ぜない
* [ ] コードのインデントを揃える

この２点を修正お願いします。

2022-08-13 04:48 UTC, func09 commented on 01.fizzbuzz/fizzbuzz.rb
> +end
インデントに「タブ」や「スペース」が混じっているので統一しましょう。
Rubyでは「タブ」は使わず。スペース２つでインデントを整えます。

```suggestion
20.times do
  numbers += 1
  if numbers % 3 == 0 && numbers % 5 == 0
    puts 'FizzBuzz'
  elsif numbers % 3 == 0
    puts 'Fizz'
  elsif numbers % 5 == 0
    puts 'Buzz'
  else
    puts numbers
  end
end
```

2022-08-13 04:48 UTC, func09 commented on 04.bowling/bowling.rb
> +score = ARGV[0]
プルリクエストに別の提出物を混ぜないようにしてください。

2022-08-13 12:10 UTC, Cephas604 commented on 04.bowling/bowling.rb
> +score = ARGV[0]
bowlingブランチから当ブランチを作成してしまったために、ボウリングスコア計算プログラムの提出物が入ってしまいました。
以後そのようなことがないように、毎度作成元ブランチを指定するよう気を付けます。

2022-08-13 12:20 UTC, Cephas604 commented on 01.fizzbuzz/fizzbuzz.rb
> +end
すみません。
スペース２つでインデントとするのは存じておりました。
しかし、Vimの設定でタブ幅がスペース２つ分となっていて、かつタブとスペースが視覚的に区別しにくくなっていたため確認漏れしてしまいました。
先程、タブ幅スペース４つ分にし、タブには印がつくようにVimを設定しなおしました。
また、これからはGitHub.com上でも確認します。

2022-08-13 12:22 UTC, Cephas604 commented
修正しました。確認お願いします。

2022-08-15 09:31 UTC, func09 commented on 01.fizzbuzz/fizzbuzz.rb
> +end
> しかし、Vimの設定でタブ幅がスペース２つ分となっていて、かつタブとスペースが視覚的に区別しにくくなっていたため確認漏れしてしまいました。

なるほど、了解です！
修正いただいて感謝です！

2022-08-15 09:32 UTC, func09 commented on 04.bowling/bowling.rb
> +score = ARGV[0]
ありがとうございます！
細かい点なのですが、提出物単位でわかりやすくするためにご協力お願いします！

2022-08-15 09:33 UTC, func09 approved these changes
LGTM!
再提出ありがとうございます！確認OKです！

2022-08-23 11:20 UTC, merged